release: ENVIRONMENT = "release"
debug:   ENVIRONMENT = "debug"

ARDOOR_DIR = $$PWD
BUILDPATH = $$ARDOOR_DIR/Build/$$ENVIRONMENT
DESTDIR = $$BUILDPATH

OBJECTS_DIR = $$DESTDIR/obj
MOC_DIR = $$DESTDIR/moc
RCC_DIR = $$DESTDIR/qrc
UI_DIR = $$DESTDIR/ui

LIBS += -L$$DESTDIR
INCLUDEPATH += $$PWD/Common

debug {
    QMAKE_CXXFLAGS += -DDEBUG=1
}

win32 {
    DEFINES += WIN32
}
